### ISSUE TITLE
[Unet3d] dataset preprocessing error

### ISSUE THREAD

**Issue by lyly403** [ltechkorea/training_results_v1.1-pre#15]
**command**
`docker run --ipc=host -it --rm --runtime=nvidia -v DATASET_DIR:/data preprocessing:latest`
**error**
`docker: Error response from daemon: Unknown runtime specified nvidia.`

**solution**

- [x] restart docker `sudo systemctl restart docker`

**Comment by jay-huh** [comment]
문제 없으므로 닫습니다.
